# Generated by Django 5.1.6 on 2025-02-28 10:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=2, unique=True, verbose_name='Plan Code')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Plan Name')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Plan Cost')),
                ('is_active', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_changed', models.DateTimeField(default=django.utils.timezone.now)),
                ('description1', models.CharField(max_length=300, verbose_name='Plan description 1')),
                ('description2', models.CharField(max_length=300, verbose_name='Plan description 2')),
                ('external_plan_id', models.CharField(max_length=256, unique=True, verbose_name='External plan id')),
                ('external_api_url', models.CharField(max_length=2000, verbose_name='External API URL')),
                ('external_style_json', models.CharField(max_length=2000, verbose_name='External Style(json)')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Subscription Cost')),
                ('external_subscription_id', models.CharField(max_length=256, verbose_name='External Subscription ID')),
                ('is_active', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.planchoice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
