# Generated by Django 5.1.6 on 2025-02-28 11:00

from django.db import migrations


def populate_plan_choice(apps, schema_editor):
    PlanChoice = apps.get_model("client", "PlanChoice")
    PlanChoice.objects.create(
        plan_code="ST",
        name="Standard",
        cost="3.00",
        is_active=True,
        description1="Get access to standard articles and reports",
        description2="Limited Access",
        external_plan_id="P-3XA93630FJ5776532M7GDXGY",
        external_api_url="https://www.paypal.com/sdk/js?client-id=AReCEa-12SLN7hVKpcb4AT2iwdS7q8_v1P9w9BDjYl0VgKaijrxkdr_574lk9NXfYgqFujb-wyVO0JnN&vault=true&intent=subscription",
        external_style_json="""{
            shape: "rect",
            color: "silver",
            layout: "vertical",
            label: "subscribe",    
        }
        """,
    )
    PlanChoice.objects.create(
        plan_code="PR",
        name="Premium",
        cost="9.00",
        is_active=True,
        description1="Get access to premium articles and reports",
        description2="Full Access",
        external_plan_id="P-74W541974F446624HM7GDX2Y",
        external_api_url="https://www.paypal.com/sdk/js?vault=true&intent=subscription",
        external_style_json="""{
            shape: "rect",
            color: "silver",
            layout: "vertical",
            label: "subscribe",    
        }
        """,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [migrations.RunPython(populate_plan_choice)]
