# Generated by Django 5.1.6 on 2025-03-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20250228_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='external_subscription_id',
            field=models.CharField(max_length=256, unique=True, verbose_name='External Subscription ID'),
        ),
    ]
