# Generated by Django 5.1.6 on 2025-02-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_writer',
            field=models.BooleanField(default=False, verbose_name='user is a writer?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=160, verbose_name='last name'),
        ),
    ]
