# Generated by Django 5.1.6 on 2025-03-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('accounts', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
    ]
