# Generated by Django 5.1.6 on 2025-03-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20250309_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='username', max_length=100, verbose_name='username'),
            preserve_default=False,
        ),
    ]
